// Mock data for demo - replace with Supabase when client approves
import type { AgentProfile, Listing, Review, Recommendation, Neighborhood } from './types';

export const agentProfile: AgentProfile = {
  id: '1',
  name: 'Elisa Rocha',
  title: 'REALTOR®',
  phone: '(832) 797-1410',
  email: 'contact@elisarocha.com',
  photo_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=500&fit=crop',
  bio: `As a Houston native with 15 years of prior experience co-owning a home security business, I bring a unique perspective to real estate. My expertise in marketing, finance, and business management ensures a stress-free home buying or selling experience for every client.

I have a particular passion for assisting veterans and first-time homebuyers, inspired by my husband's military service. As a mother of three, I understand the importance of finding the perfect home for your family.

Beyond real estate, I'm actively involved in my community, volunteering with schools, foster homes, and my church. My approach is built on trust, transparency, and tireless dedication. I don't just close deals—I build lasting relationships with my clients, many of whom return for their future real estate needs or refer their friends and family.`,
  har_url: 'https://www.har.com/elisa-rocha/agent_EROSAO',
  license_number: 'TX-123456',
  years_experience: 15,
  total_sales: 50,
  total_volume: 25000000,
  updated_at: new Date().toISOString(),
};

export const listings: Listing[] = [
  {
    id: '1',
    har_listing_id: 'HAR-001',
    address: '4521 River Oaks Boulevard',
    city: 'Houston',
    state: 'TX',
    zip: '77027',
    price: 2450000,
    bedrooms: 5,
    bathrooms: 4.5,
    sqft: 5800,
    lot_size: '0.45 acres',
    year_built: 2018,
    property_type: 'Single Family',
    status: 'active',
    sold_date: null,
    sold_price: null,
    listing_date: '2024-01-10',
    description: 'Stunning contemporary masterpiece in the heart of River Oaks. This exceptional home features soaring ceilings, floor-to-ceiling windows, and premium finishes throughout. The gourmet kitchen boasts top-of-the-line appliances, marble countertops, and a large island perfect for entertaining. The primary suite is a true retreat with a spa-like bathroom and custom closet. Outdoor living includes a resort-style pool, covered patio, and meticulously landscaped grounds.',
    features: ['Pool', 'Smart Home', 'Wine Cellar', 'Home Theater', 'Gated', '3-Car Garage', 'Chef\'s Kitchen', 'Primary Suite on Main'],
    images: ['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop'],
    har_url: 'https://www.har.com/listing/1',
    latitude: 29.7518,
    longitude: -95.4291,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    har_listing_id: 'HAR-002',
    address: '1847 Heights Boulevard',
    city: 'Houston',
    state: 'TX',
    zip: '77008',
    price: 875000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 2850,
    lot_size: '0.18 acres',
    year_built: 2020,
    property_type: 'Single Family',
    status: 'active',
    sold_date: null,
    sold_price: null,
    listing_date: '2024-01-05',
    description: 'Modern farmhouse charm meets urban living in this stunning Heights home. Open concept living with hardwood floors, shiplap accents, and designer lighting. The chef\'s kitchen features quartz countertops, a large island, and premium SS appliances. Spacious backyard with covered patio perfect for Houston\'s outdoor lifestyle.',
    features: ['Hardwood Floors', 'Open Floor Plan', 'Covered Patio', 'Energy Efficient', 'Walk to Shops', '2-Car Garage'],
    images: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop', 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop'],
    har_url: 'https://www.har.com/listing/2',
    latitude: 29.7850,
    longitude: -95.3950,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    har_listing_id: 'HAR-003',
    address: '2201 Memorial Drive',
    city: 'Houston',
    state: 'TX',
    zip: '77007',
    price: 1650000,
    bedrooms: 4,
    bathrooms: 4,
    sqft: 4200,
    lot_size: '0.32 acres',
    year_built: 2015,
    property_type: 'Single Family',
    status: 'sold',
    sold_date: '2024-01-08',
    sold_price: 1625000,
    listing_date: '2023-11-15',
    description: 'Elegant Memorial area home with stunning views. This beautifully maintained property features high-end finishes, an open floor plan, and exceptional outdoor living spaces. Perfect for entertaining with a gourmet kitchen, formal dining, and a sparkling pool.',
    features: ['Pool', 'Updated Kitchen', 'High Ceilings', 'Formal Dining', 'Study', 'Game Room'],
    images: ['https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=600&fit=crop'],
    har_url: 'https://www.har.com/listing/3',
    latitude: 29.7610,
    longitude: -95.4140,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    har_listing_id: 'HAR-004',
    address: '5623 Tanglewood Drive',
    city: 'Houston',
    state: 'TX',
    zip: '77056',
    price: 1895000,
    bedrooms: 5,
    bathrooms: 4.5,
    sqft: 4800,
    lot_size: '0.38 acres',
    year_built: 2012,
    property_type: 'Single Family',
    status: 'sold',
    sold_date: '2023-12-20',
    sold_price: 1875000,
    listing_date: '2023-10-01',
    description: 'Gorgeous Tanglewood estate on a tree-lined street. Completely renovated with no expense spared. Features include a stunning primary suite, chef\'s kitchen, media room, and a backyard oasis with pool and outdoor kitchen.',
    features: ['Pool', 'Outdoor Kitchen', 'Media Room', 'Wine Room', 'Generator', 'Elevator Ready'],
    images: ['https://images.unsplash.com/photo-1600573472550-8090b5e0745e?w=800&h=600&fit=crop'],
    har_url: 'https://www.har.com/listing/4',
    latitude: 29.7420,
    longitude: -95.4580,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    har_listing_id: 'HAR-005',
    address: '789 Midtown Avenue #2401',
    city: 'Houston',
    state: 'TX',
    zip: '77002',
    price: 595000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1450,
    lot_size: null,
    year_built: 2019,
    property_type: 'Condo',
    status: 'active',
    sold_date: null,
    sold_price: null,
    listing_date: '2024-01-12',
    description: 'Luxury high-rise living in the heart of Midtown. This stunning corner unit features panoramic city views, floor-to-ceiling windows, and top-tier finishes. Building amenities include 24-hour concierge, rooftop pool, fitness center, and secure parking.',
    features: ['City Views', 'Concierge', 'Rooftop Pool', 'Fitness Center', 'Secure Parking', 'Pet Friendly'],
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop'],
    har_url: 'https://www.har.com/listing/5',
    latitude: 29.7520,
    longitude: -95.3770,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    har_listing_id: 'HAR-006',
    address: '3456 West University Boulevard',
    city: 'Houston',
    state: 'TX',
    zip: '77005',
    price: 1275000,
    bedrooms: 4,
    bathrooms: 3.5,
    sqft: 3400,
    lot_size: '0.22 acres',
    year_built: 2017,
    property_type: 'Single Family',
    status: 'sold',
    sold_date: '2023-11-30',
    sold_price: 1255000,
    listing_date: '2023-09-15',
    description: 'Beautiful West University home in top-rated school district. This well-designed home features an open floor plan, gourmet kitchen, and spacious bedrooms. The backyard is perfect for family activities with room for a future pool.',
    features: ['Top Schools', 'Open Floor Plan', 'Island Kitchen', 'Study', 'Large Backyard', 'Mud Room'],
    images: ['https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800&h=600&fit=crop'],
    har_url: 'https://www.har.com/listing/6',
    latitude: 29.7180,
    longitude: -95.4230,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const reviews: Review[] = [
  {
    id: '1',
    har_review_id: 'REV-001',
    reviewer_name: 'Jennifer & Michael Thompson',
    reviewer_photo_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop',
    rating: 5,
    review_text: 'Elisa was absolutely incredible to work with! As first-time homebuyers, we were nervous about the process, but Elisa made everything so smooth. She was patient with our questions, quick to respond, and truly had our best interests at heart. She found us our dream home in the Heights and negotiated an amazing deal. We couldn\'t be happier!',
    review_date: '2024-01-05',
    transaction_type: 'Bought',
    property_address: 'Heights, Houston',
    har_url: 'https://www.har.com/realestatepro/ratingshare/98BFD528-2CFD-4D19-9F7D-C9EB84D513B7',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    har_review_id: 'REV-002',
    reviewer_name: 'Robert Chen',
    reviewer_photo_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop',
    rating: 5,
    review_text: 'I\'ve bought and sold multiple properties with Elisa over the years, and she never disappoints. Her market knowledge is exceptional, and she always goes above and beyond for her clients. She recently helped me sell my Memorial home for above asking price in just 10 days. Highly recommend!',
    review_date: '2023-12-18',
    transaction_type: 'Sold',
    property_address: 'Memorial, Houston',
    har_url: 'https://www.har.com/realestatepro/ratingshare/98BFD528-2CFD-4D19-9F7D-C9EB84D513B7',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    har_review_id: 'REV-003',
    reviewer_name: 'Sarah Martinez',
    reviewer_photo_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    rating: 5,
    review_text: 'Elisa helped us find the perfect family home in West University. Her knowledge of the school districts and neighborhoods was invaluable. She was always available, even on weekends, and made the whole process enjoyable. Our kids love our new home, and we have Elisa to thank!',
    review_date: '2023-11-25',
    transaction_type: 'Bought',
    property_address: 'West University, Houston',
    har_url: 'https://www.har.com/realestatepro/ratingshare/98BFD528-2CFD-4D19-9F7D-C9EB84D513B7',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    har_review_id: 'REV-004',
    reviewer_name: 'David & Lisa Park',
    reviewer_photo_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    rating: 5,
    review_text: 'We relocated from California and didn\'t know Houston at all. Elisa took the time to show us different neighborhoods and helped us understand what would work best for our lifestyle. She was incredibly knowledgeable and made our transition seamless. We found the perfect home in Tanglewood and couldn\'t be happier.',
    review_date: '2023-10-30',
    transaction_type: 'Bought',
    property_address: 'Tanglewood, Houston',
    har_url: 'https://www.har.com/realestatepro/ratingshare/98BFD528-2CFD-4D19-9F7D-C9EB84D513B7',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    har_review_id: 'REV-005',
    reviewer_name: 'Amanda Wilson',
    reviewer_photo_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop',
    rating: 5,
    review_text: 'Selling my late mother\'s home was emotional and overwhelming, but Elisa handled everything with such care and professionalism. She was sensitive to my situation, gave me time when I needed it, and ultimately got a great price for the property. I\'m so grateful for her support during a difficult time.',
    review_date: '2023-09-15',
    transaction_type: 'Sold',
    property_address: 'River Oaks, Houston',
    har_url: 'https://www.har.com/realestatepro/ratingshare/98BFD528-2CFD-4D19-9F7D-C9EB84D513B7',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    har_review_id: 'REV-006',
    reviewer_name: 'James & Emily Rodriguez',
    reviewer_photo_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    rating: 5,
    review_text: 'Five stars isn\'t enough for Elisa! She helped us sell our starter home and buy our forever home in the same month. The coordination was complex, but she made it look easy. Her negotiation skills saved us over $30,000 combined on both transactions. We\'ve already referred her to three friends.',
    review_date: '2023-08-22',
    transaction_type: 'Bought & Sold',
    property_address: 'Heights & Memorial, Houston',
    har_url: 'https://www.har.com/realestatepro/ratingshare/98BFD528-2CFD-4D19-9F7D-C9EB84D513B7',
    created_at: new Date().toISOString(),
  },
];

export const recommendations: Recommendation[] = [
  {
    id: '1',
    har_rec_id: 'REC-001',
    recommender_name: 'Maria Santos',
    recommender_title: 'Senior Loan Officer, First National Bank',
    relationship: 'Professional Partner',
    recommendation_text: 'I\'ve worked with Elisa on dozens of transactions, and she is hands-down one of the best realtors in Houston. Her attention to detail, communication skills, and dedication to her clients make every transaction smooth. She ensures her clients are well-prepared and always meets deadlines. Any lender would be lucky to work with her.',
    recommendation_date: '2023-12-01',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    har_rec_id: 'REC-002',
    recommender_name: 'Thomas Wright',
    recommender_title: 'Real Estate Attorney',
    relationship: 'Professional Partner',
    recommendation_text: 'In my 20 years of real estate law, few agents stand out like Elisa Rocha. Her professionalism, market expertise, and ethical standards are exemplary. She thoroughly prepares her clients and ensures all documentation is in order, making closings seamless. I highly recommend her to anyone buying or selling property in Houston.',
    recommendation_date: '2023-10-15',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    har_rec_id: 'REC-003',
    recommender_name: 'Patricia Lee',
    recommender_title: 'Interior Designer',
    relationship: 'Colleague',
    recommendation_text: 'Elisa has a remarkable eye for potential in properties. She often brings me in to help her clients visualize improvements, and her insights are always spot-on. She genuinely cares about her clients\' happiness, not just closing deals. Her staging recommendations alone have helped properties sell faster and for more money.',
    recommendation_date: '2023-09-20',
    created_at: new Date().toISOString(),
  },
];

export const neighborhoods: Neighborhood[] = [
  {
    id: '1',
    name: 'River Oaks',
    slug: 'river-oaks',
    description: 'River Oaks is Houston\'s most prestigious neighborhood, known for its stately mansions, tree-lined streets, and proximity to River Oaks Country Club. This exclusive enclave offers a blend of historic estates and modern architectural masterpieces. Residents enjoy access to world-class shopping at River Oaks District, fine dining, and some of the city\'s best private schools.',
    image_url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=400&fit=crop',
    avg_price: 2800000,
    total_listings: 45,
    har_url: 'https://www.har.com/riveroaks',
    highlights: ['Prestigious Address', 'Historic & Modern Homes', 'Top Private Schools', 'River Oaks Country Club', 'Luxury Shopping', 'Fine Dining'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'The Heights',
    slug: 'the-heights',
    description: 'The Heights combines historic charm with urban vibrancy. Known for its Victorian bungalows, tree-lined streets, and strong sense of community, this neighborhood has become one of Houston\'s most sought-after areas. Enjoy walkable streets, local boutiques, farm-to-table restaurants, and a thriving arts scene along 19th Street.',
    image_url: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=400&fit=crop',
    avg_price: 725000,
    total_listings: 78,
    har_url: 'https://www.har.com/heights',
    highlights: ['Historic Character', 'Walkable Streets', 'Local Boutiques', '19th Street Scene', 'Family Friendly', 'Strong Community'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Memorial',
    slug: 'memorial',
    description: 'Memorial offers a perfect blend of suburban tranquility and urban convenience. With excellent schools, large lots, and mature trees, it\'s ideal for families. The neighborhood provides easy access to Memorial Park, one of the largest urban parks in the nation, and the Energy Corridor business district.',
    image_url: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=800&h=400&fit=crop',
    avg_price: 1200000,
    total_listings: 62,
    har_url: 'https://www.har.com/memorial',
    highlights: ['Top Schools', 'Large Lots', 'Memorial Park Access', 'Family Oriented', 'Mature Trees', 'Energy Corridor Access'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'West University',
    slug: 'west-university',
    description: 'West University Place is an incorporated city within Houston known for its top-rated schools, walkable streets, and strong property values. This family-oriented community features well-maintained homes, tree-lined sidewalks, and a charming village atmosphere with local shops and restaurants.',
    image_url: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=400&fit=crop',
    avg_price: 1350000,
    total_listings: 35,
    har_url: 'https://www.har.com/westuniversity',
    highlights: ['Top-Rated Schools', 'Village Atmosphere', 'Strong Property Values', 'Walkable', 'Safe Community', 'Near Rice Village'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Tanglewood',
    slug: 'tanglewood',
    description: 'Tanglewood is an established, prestigious neighborhood known for its large lots, mature landscaping, and elegant homes. Located near the Galleria, residents enjoy easy access to world-class shopping, dining, and entertainment while living in a quiet, residential setting.',
    image_url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=400&fit=crop',
    avg_price: 1750000,
    total_listings: 28,
    har_url: 'https://www.har.com/tanglewood',
    highlights: ['Large Lots', 'Galleria Access', 'Established Community', 'Elegant Homes', 'Great Schools', 'Quiet Streets'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Midtown',
    slug: 'midtown',
    description: 'Midtown is Houston\'s urban core, perfect for those who love city living. This vibrant neighborhood features trendy restaurants, rooftop bars, art galleries, and easy access to downtown. With a mix of high-rise condos, townhomes, and lofts, Midtown attracts young professionals and urban enthusiasts.',
    image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=400&fit=crop',
    avg_price: 425000,
    total_listings: 92,
    har_url: 'https://www.har.com/midtown',
    highlights: ['Urban Living', 'Nightlife Scene', 'Walkable', 'Near Downtown', 'Condos & Townhomes', 'Young & Vibrant'],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
